# Generated by Django 5.0.6 on 2025-04-21 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0002_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='parent_center',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_subcenter': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hq.center'),
        ),
        migrations.AlterField(
            model_name='center',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
