# Generated by Django 5.0.6 on 2025-04-20 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='center',
            name='location',
        ),
        migrations.AlterField(
            model_name='center',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcenter_center', to=settings.AUTH_USER_MODEL),
        ),
    ]
